const ar=[10,20,30,40];
console.log(ar);
const st =["rayhan", "mamun" , "kamal"];
console.log(st);
const bl=[true, true , false, false, true];
console.log(bl.length);
const a=[39,4,3,4,3,5,3,54,4];
console.log(a.length);
console.log(a[2]);
const op= (a[3]);
console.log(op);
a[1]=300;
console.log(a);